name: CI Pipeline

on:
  push:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        pip install --no-cache-dir -r requirements.txt
        pip install pytest flake8 torch torchvision matplotlib pillow numpy

    - name: Run linter (flake8)
      run: flake8 code/ tests/

    - name: Run unit tests
      run: pytest

    - name: Build Docker Image
      run: docker build -t davbnn/ai-univr-project .

    - name: Train and save model
      run: |
        python3 code/train.py
        echo "Model saved as model.pt"

        - name: Upload trained model as artifact
        uses: actions/upload-artifact@v4
        with:
          name: trained-model
          path: model.pt
      

    - name: Docker Login
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Docker Push
      run: docker push davbnn/ai-univr-project
